theme: jekyll-theme-minimal
title: Sridhar's HomePage
description: Bookmark this to keep an eye on my project updates!
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - _plugins/generate_links.rb
